# Dataset Paths
birb_20_path: '/mnt/work4/datasets/lyh/birdsong-recognition'
birb_21_path: '/mnt/work4/datasets/lyh/birdclef-2021'
birb_22_path: '/mnt/work4/datasets/lyh/birdclef-2022'
xc_am_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-a-m'
xc_nz_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-n-z'
birb_23_path: '/mnt/work4/datasets/lyh/birdclef-2023'

birdvox_path: "/mnt/work2/users/lyh/datasets/BirdVox-DCASE-20k"
ff1010_path: "/mnt/work2/users/lyh/datasets/ff1010bird"

init_ckpt: 
exp_dir: 'results/ft/b0-leaf-test'

ft_stage: 2
filter_tail: True
upsample_thr: True
downsample_thr: 
seed: 2023
fold: 0

batch_size: 32
ngpus: 2
accumulate_grad_batches: 1
use_fp16: False
epochs: 50
lr: 1e-4
criterion: 2way

duration: 10
mixup_prob: 0.5

base_model_name: "tf_efficientnet_b0_ns"
pretrained: True
in_channels: 1

feat: leaf    # 'spec', 'mel_spec', 'tl_spec', 'kaldi_fb', 'leaf'
n_fft: 2048
n_mels: 64
hop_length: 512
img_len:
sample_rate: 16000
fmin: 80
fmax: 16000