# Dataset Paths
birb_20_path: 'D:/birdclef/birbclef/conf/birdsong-recognition'
birb_21_path: 'D:/birdclef/birbclef/conf/birdclef-2021'
birb_22_path: 'D:/birdclef/birbclef/conf/birdclef-2022'
xc_am_path: 'D:/birdclef/birbclef/conf/xeno-canto-bird-recordings-extended-a-m'
xc_nz_path: 'D:/birdclef/birbclef/conf/xeno-canto-bird-recordings-extended-n-z'
birb_23_path: 'D:/birdclef/birbclef/conf/birdclef-2023'

birdvox_path: "D:/birdclef/birbclef/conf/BirdVox-DCASE-20k"
ff1010_path: "D:/birdclef/birbclef/conf/ff1010bird"
PolandNFC_path: "D:/birdclef/birbclef/conf/PolandNFC_test_wav"
chern_wav_path: "D:/birdclef/birbclef/conf/chern_wav"
wabrlrb10k_path: "D:/birdclef/birbclef/conf/wabrlrb10k"

# init_ckpt: 'audio_mae/pretrained.pth'
init_ckpt: 
exp_dir: 'D:/birdclef/birbclef/results/ft/ft-check'

ft_stage: 2
filter_tail: True
upsample_thr: True
downsample_thr: 
seed: 2023
fold: 1

batch_size: 32
ngpus: 2
accumulate_grad_batches: 1
use_fp16: True
epochs: 30
lr: 1e-4
criterion: ce     # 'focal', 'bce', 'ce'

feat: kaldi_fb    # 'spec', 'mel_spec', 'tl_spec', 'kaldi_fb', 'leaf'
img_len: 1024
duration: 10
n_mels: 128
depth: 6
embed_dim: 768
num_heads: 12

mask_t_prob: 0.3
mask_f_prob: 0.3
mixup_prob: 0.5

sample_rate: 32000
fmin: 80
fmax: 16000