# Dataset Paths
birb_20_path: '/mnt/work4/datasets/lyh/birdsong-recognition'
birb_21_path: '/mnt/work4/datasets/lyh/birdclef-2021'
birb_22_path: '/mnt/work4/datasets/lyh/birdclef-2022'
xc_am_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-a-m'
xc_nz_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-n-z'
birb_23_path: '/mnt/work4/datasets/lyh/birdclef-2023'

init_ckpt: 'audio_mae/pretrained.pth'
exp_dir: 'results/pt/enc6L-dec8L-lr1e-4-kaldifb'

batch_size: 32
ngpus: 2
accumulate_grad_batches: 8
use_fp16: True
epochs: 100
lr: 1e-4

feat: fb
duration: 10.26   # for target_len 1024
img_len: 1024
melbins: 128
depth: 6
decoder_depth: 8
embed_dim: 768
num_heads: 12

normalize_spec: True
mask_ratio: 0.8