# Dataset Paths
birb_20_path: '/mnt/work4/datasets/lyh/birdsong-recognition'
birb_21_path: '/mnt/work4/datasets/lyh/birdclef-2021'
birb_22_path: '/mnt/work4/datasets/lyh/birdclef-2022'
xc_am_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-a-m'
xc_nz_path: '/mnt/work4/datasets/lyh/xeno-canto-bird-recordings-extended-n-z'
birb_23_path: '/mnt/work4/datasets/lyh/birdclef-2023'

ckpt: 'audio_mae/pretrained.pth'
exp_dir: 'results/pt/6L-first-try'

batch_size: 32
ngpus: 4
accumulate_grad_batches: 4
use_fp16: False
epochs: 32
lr: 2e-4

mask_ratio: 0.8
depth: 6